#!/usr/bin/env python3
"""
Traffic Stop Bootcamp wordmark — source file.

The three SVGs in assets/img/ are generated by this script. The lettering is
converted to outlines, so the finished files need no font to render anywhere;
this script is what you edit if the wordmark itself has to change.

    pip3 install fonttools
    python3 assets/img/logo-source/build-logo.py

Typeface is Avenir Next Condensed, which ships with macOS — a condensed
grotesque chosen to sit in the same family as the Journey 2 Justice Learning
mark (assets/img/logo-j2j.png), whose structure this follows: a black tile,
one large line, and a thin tracked word held between two rules.
"""
import os
from fontTools.ttLib import TTCollection
from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.pens.transformPen import TransformPen
from fontTools.misc.transform import Transform

TTC = "/System/Library/Fonts/Avenir Next Condensed.ttc"
FACES = {"bold": 0, "demibold": 2, "medium": 5, "regular": 7, "ultralight": 10}
OUT = os.path.join(os.path.dirname(__file__), "..")

_c = {}
def face(n):
    if n not in _c:
        f = TTCollection(TTC).fonts[FACES[n]]
        _c[n] = (f.getGlyphSet(), f["cmap"].getBestCmap(), f["head"].unitsPerEm)
    return _c[n]

def measure(t, n, size, track):
    gs, cmap, upem = face(n)
    return sum(gs[cmap[ord(ch)]].width * size / upem for ch in t) + track * (len(t) - 1)

def path(t, n, size, track, x, y):
    """Outlines for `t`, baseline at y, left edge at x."""
    gs, cmap, upem = face(n)
    s = size / upem
    out, cx = [], x
    for ch in t:
        g = cmap[ord(ch)]
        pen = SVGPathPen(gs)
        gs[g].draw(TransformPen(pen, Transform(s, 0, 0, -s, cx, y)))
        d = pen.getCommands()
        if d:
            out.append(d)
        cx += gs[g].width * s + track
    return " ".join(out)

def write(name, w, h, body, label):
    svg = (f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {w} {h}" width="{w}" '
           f'height="{h}" role="img" aria-label="{label}">\n  ' + "\n  ".join(body) + "\n</svg>\n")
    p = os.path.join(OUT, name)
    open(p, "w").write(svg)
    print("wrote", p, f"({len(svg)} bytes)")

def rules(parts, m, meas, word_x, word_w, y, h, gap=24, color="#FFFFFF"):
    parts.append(f'<rect x="{m}" y="{y}" width="{word_x-gap-m:.1f}" height="{h}" fill="{color}"/>')
    rx = word_x + word_w + gap
    parts.append(f'<rect x="{rx:.1f}" y="{y}" width="{m+meas-rx:.1f}" height="{h}" fill="{color}"/>')


def logo_wide():
    """Primary lockup — used in the site header, where width is what's free."""
    W, H, M = 760, 320, 52
    MEAS = W - 2 * M
    p = [f'<rect width="{W}" height="{H}" rx="7" fill="#000000"/>']

    top, size = "TRAFFIC STOP", 118
    track = (MEAS - measure(top, "regular", size, 0)) / (len(top) - 1)
    p.append(f'<path fill="#FFFFFF" d="{path(top,"regular",size,track,M,168)}"/>')

    b, bsize, btrack = "BOOTCAMP", 56, 13.0
    bw = measure(b, "ultralight", bsize, btrack)
    bx = M + (MEAS - bw) / 2
    p.append(f'<path fill="#FFFFFF" d="{path(b,"ultralight",bsize,btrack,bx,250)}"/>')
    rules(p, M, MEAS, bx, bw, 228, 2.2)

    write("logo.svg", W, H, p, "Traffic Stop Bootcamp")


def logo_stacked():
    """Square alternate — for social avatars, slides, anywhere width is tight."""
    W, H, M = 600, 560, 62
    MEAS = W - 2 * M
    p = [f'<rect width="{W}" height="{H}" rx="7" fill="#000000"/>']

    t1 = (MEAS - measure("TRAFFIC", "regular", 104, 0)) / 6
    p.append(f'<path fill="#C9C9C9" d="{path("TRAFFIC","regular",104,t1,M,214)}"/>')

    sw = measure("STOP", "regular", 104, 16.0)
    sx = M + (MEAS - sw) / 2
    p.append(f'<path fill="#FFFFFF" d="{path("STOP","regular",104,16.0,sx,330)}"/>')
    rules(p, M, MEAS, sx, sw, 292, 2.6, gap=26)

    t3 = (MEAS - measure("BOOTCAMP", "ultralight", 64, 0)) / 7
    p.append(f'<path fill="#FFFFFF" d="{path("BOOTCAMP","ultralight",64,t3,M,432)}"/>')

    write("logo-stacked.svg", W, H, p, "Traffic Stop Bootcamp")


def favicon():
    """Three letters is all that survives 16px, so the mark reduces to TSB —
    set bold and pushed out to the edges, because a favicon with polite
    margins is a smudge at the size it is actually seen."""
    W, M = 64, 5
    p = [f'<rect width="{W}" height="{W}" rx="8" fill="#000000"/>']
    t, size = "TSB", 36            # largest that fits three letters without crowding
    track = ((W - 2 * M) - measure(t, "bold", size, 0)) / (len(t) - 1)
    cap = size * 0.72              # optical centring on the cap height
    p.append(f'<path fill="#FFFFFF" d="{path(t,"bold",size,track,M,(W+cap)/2)}"/>')
    write("mark.svg", W, W, p, "Traffic Stop Bootcamp")


if __name__ == "__main__":
    logo_wide()
    logo_stacked()
    favicon()
